/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as FragrancesRouteRouteImport } from './routes/fragrances/route'
import { Route as CollectionsRouteRouteImport } from './routes/collections/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as FragrancesIndexRouteImport } from './routes/fragrances/index'
import { Route as AuthAccountRecoveryRouteImport } from './routes/auth/account-recovery'
import { Route as UsersIdRouteRouteImport } from './routes/users/$id/route'
import { Route as FragrancesIdRouteRouteImport } from './routes/fragrances/$id/route'
import { Route as CollectionsIdRouteRouteImport } from './routes/collections/$id/route'
import { Route as UsersIdIndexRouteImport } from './routes/users/$id/index'
import { Route as FragrancesIdIndexRouteImport } from './routes/fragrances/$id/index'
import { Route as UsersIdReviewsRouteImport } from './routes/users/$id/reviews'
import { Route as UsersIdLikesRouteImport } from './routes/users/$id/likes'
import { Route as FragrancesIdReviewRouteRouteImport } from './routes/fragrances/$id/review/route'
import { Route as FragrancesIdReviewIndexRouteImport } from './routes/fragrances/$id/review/index'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesRouteRoute = FragrancesRouteRouteImport.update({
  id: '/fragrances',
  path: '/fragrances',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRouteRoute = CollectionsRouteRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRouteRoute,
} as any)
const FragrancesIndexRoute = FragrancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FragrancesRouteRoute,
} as any)
const AuthAccountRecoveryRoute = AuthAccountRecoveryRouteImport.update({
  id: '/auth/account-recovery',
  path: '/auth/account-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRouteRoute = UsersIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UsersRouteRoute,
} as any)
const FragrancesIdRouteRoute = FragrancesIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FragrancesRouteRoute,
} as any)
const CollectionsIdRouteRoute = CollectionsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollectionsRouteRoute,
} as any)
const UsersIdIndexRoute = UsersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersIdRouteRoute,
} as any)
const FragrancesIdIndexRoute = FragrancesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FragrancesIdRouteRoute,
} as any)
const UsersIdReviewsRoute = UsersIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UsersIdRouteRoute,
} as any)
const UsersIdLikesRoute = UsersIdLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => UsersIdRouteRoute,
} as any)
const FragrancesIdReviewRouteRoute = FragrancesIdReviewRouteRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => FragrancesIdRouteRoute,
} as any)
const FragrancesIdReviewIndexRoute = FragrancesIdReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FragrancesIdReviewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteRouteWithChildren
  '/fragrances': typeof FragrancesRouteRouteWithChildren
  '/search': typeof SearchRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteRoute
  '/fragrances/$id': typeof FragrancesIdRouteRouteWithChildren
  '/users/$id': typeof UsersIdRouteRouteWithChildren
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/fragrances/': typeof FragrancesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/users/': typeof UsersIndexRoute
  '/fragrances/$id/review': typeof FragrancesIdReviewRouteRouteWithChildren
  '/users/$id/likes': typeof UsersIdLikesRoute
  '/users/$id/reviews': typeof UsersIdReviewsRoute
  '/fragrances/$id/': typeof FragrancesIdIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
  '/fragrances/$id/review/': typeof FragrancesIdReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteRoute
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/fragrances': typeof FragrancesIndexRoute
  '/search': typeof SearchIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/$id/likes': typeof UsersIdLikesRoute
  '/users/$id/reviews': typeof UsersIdReviewsRoute
  '/fragrances/$id': typeof FragrancesIdIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
  '/fragrances/$id/review': typeof FragrancesIdReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRouteRouteWithChildren
  '/fragrances': typeof FragrancesRouteRouteWithChildren
  '/search': typeof SearchRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/collections/$id': typeof CollectionsIdRouteRoute
  '/fragrances/$id': typeof FragrancesIdRouteRouteWithChildren
  '/users/$id': typeof UsersIdRouteRouteWithChildren
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/fragrances/': typeof FragrancesIndexRoute
  '/search/': typeof SearchIndexRoute
  '/users/': typeof UsersIndexRoute
  '/fragrances/$id/review': typeof FragrancesIdReviewRouteRouteWithChildren
  '/users/$id/likes': typeof UsersIdLikesRoute
  '/users/$id/reviews': typeof UsersIdReviewsRoute
  '/fragrances/$id/': typeof FragrancesIdIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
  '/fragrances/$id/review/': typeof FragrancesIdReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/fragrances'
    | '/search'
    | '/users'
    | '/collections/$id'
    | '/fragrances/$id'
    | '/users/$id'
    | '/auth/account-recovery'
    | '/fragrances/'
    | '/search/'
    | '/users/'
    | '/fragrances/$id/review'
    | '/users/$id/likes'
    | '/users/$id/reviews'
    | '/fragrances/$id/'
    | '/users/$id/'
    | '/fragrances/$id/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/collections/$id'
    | '/auth/account-recovery'
    | '/fragrances'
    | '/search'
    | '/users'
    | '/users/$id/likes'
    | '/users/$id/reviews'
    | '/fragrances/$id'
    | '/users/$id'
    | '/fragrances/$id/review'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/fragrances'
    | '/search'
    | '/users'
    | '/collections/$id'
    | '/fragrances/$id'
    | '/users/$id'
    | '/auth/account-recovery'
    | '/fragrances/'
    | '/search/'
    | '/users/'
    | '/fragrances/$id/review'
    | '/users/$id/likes'
    | '/users/$id/reviews'
    | '/fragrances/$id/'
    | '/users/$id/'
    | '/fragrances/$id/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRouteRoute: typeof CollectionsRouteRouteWithChildren
  FragrancesRouteRoute: typeof FragrancesRouteRouteWithChildren
  SearchRouteRoute: typeof SearchRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  AuthAccountRecoveryRoute: typeof AuthAccountRecoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances': {
      id: '/fragrances'
      path: '/fragrances'
      fullPath: '/fragrances'
      preLoaderRoute: typeof FragrancesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRouteRoute
    }
    '/fragrances/': {
      id: '/fragrances/'
      path: '/'
      fullPath: '/fragrances/'
      preLoaderRoute: typeof FragrancesIndexRouteImport
      parentRoute: typeof FragrancesRouteRoute
    }
    '/auth/account-recovery': {
      id: '/auth/account-recovery'
      path: '/auth/account-recovery'
      fullPath: '/auth/account-recovery'
      preLoaderRoute: typeof AuthAccountRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/fragrances/$id': {
      id: '/fragrances/$id'
      path: '/$id'
      fullPath: '/fragrances/$id'
      preLoaderRoute: typeof FragrancesIdRouteRouteImport
      parentRoute: typeof FragrancesRouteRoute
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteRouteImport
      parentRoute: typeof CollectionsRouteRoute
    }
    '/users/$id/': {
      id: '/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof UsersIdIndexRouteImport
      parentRoute: typeof UsersIdRouteRoute
    }
    '/fragrances/$id/': {
      id: '/fragrances/$id/'
      path: '/'
      fullPath: '/fragrances/$id/'
      preLoaderRoute: typeof FragrancesIdIndexRouteImport
      parentRoute: typeof FragrancesIdRouteRoute
    }
    '/users/$id/reviews': {
      id: '/users/$id/reviews'
      path: '/reviews'
      fullPath: '/users/$id/reviews'
      preLoaderRoute: typeof UsersIdReviewsRouteImport
      parentRoute: typeof UsersIdRouteRoute
    }
    '/users/$id/likes': {
      id: '/users/$id/likes'
      path: '/likes'
      fullPath: '/users/$id/likes'
      preLoaderRoute: typeof UsersIdLikesRouteImport
      parentRoute: typeof UsersIdRouteRoute
    }
    '/fragrances/$id/review': {
      id: '/fragrances/$id/review'
      path: '/review'
      fullPath: '/fragrances/$id/review'
      preLoaderRoute: typeof FragrancesIdReviewRouteRouteImport
      parentRoute: typeof FragrancesIdRouteRoute
    }
    '/fragrances/$id/review/': {
      id: '/fragrances/$id/review/'
      path: '/'
      fullPath: '/fragrances/$id/review/'
      preLoaderRoute: typeof FragrancesIdReviewIndexRouteImport
      parentRoute: typeof FragrancesIdReviewRouteRoute
    }
  }
}

interface CollectionsRouteRouteChildren {
  CollectionsIdRouteRoute: typeof CollectionsIdRouteRoute
}

const CollectionsRouteRouteChildren: CollectionsRouteRouteChildren = {
  CollectionsIdRouteRoute: CollectionsIdRouteRoute,
}

const CollectionsRouteRouteWithChildren =
  CollectionsRouteRoute._addFileChildren(CollectionsRouteRouteChildren)

interface FragrancesIdReviewRouteRouteChildren {
  FragrancesIdReviewIndexRoute: typeof FragrancesIdReviewIndexRoute
}

const FragrancesIdReviewRouteRouteChildren: FragrancesIdReviewRouteRouteChildren =
  {
    FragrancesIdReviewIndexRoute: FragrancesIdReviewIndexRoute,
  }

const FragrancesIdReviewRouteRouteWithChildren =
  FragrancesIdReviewRouteRoute._addFileChildren(
    FragrancesIdReviewRouteRouteChildren,
  )

interface FragrancesIdRouteRouteChildren {
  FragrancesIdReviewRouteRoute: typeof FragrancesIdReviewRouteRouteWithChildren
  FragrancesIdIndexRoute: typeof FragrancesIdIndexRoute
}

const FragrancesIdRouteRouteChildren: FragrancesIdRouteRouteChildren = {
  FragrancesIdReviewRouteRoute: FragrancesIdReviewRouteRouteWithChildren,
  FragrancesIdIndexRoute: FragrancesIdIndexRoute,
}

const FragrancesIdRouteRouteWithChildren =
  FragrancesIdRouteRoute._addFileChildren(FragrancesIdRouteRouteChildren)

interface FragrancesRouteRouteChildren {
  FragrancesIdRouteRoute: typeof FragrancesIdRouteRouteWithChildren
  FragrancesIndexRoute: typeof FragrancesIndexRoute
}

const FragrancesRouteRouteChildren: FragrancesRouteRouteChildren = {
  FragrancesIdRouteRoute: FragrancesIdRouteRouteWithChildren,
  FragrancesIndexRoute: FragrancesIndexRoute,
}

const FragrancesRouteRouteWithChildren = FragrancesRouteRoute._addFileChildren(
  FragrancesRouteRouteChildren,
)

interface SearchRouteRouteChildren {
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteRouteChildren: SearchRouteRouteChildren = {
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteRouteWithChildren = SearchRouteRoute._addFileChildren(
  SearchRouteRouteChildren,
)

interface UsersIdRouteRouteChildren {
  UsersIdLikesRoute: typeof UsersIdLikesRoute
  UsersIdReviewsRoute: typeof UsersIdReviewsRoute
  UsersIdIndexRoute: typeof UsersIdIndexRoute
}

const UsersIdRouteRouteChildren: UsersIdRouteRouteChildren = {
  UsersIdLikesRoute: UsersIdLikesRoute,
  UsersIdReviewsRoute: UsersIdReviewsRoute,
  UsersIdIndexRoute: UsersIdIndexRoute,
}

const UsersIdRouteRouteWithChildren = UsersIdRouteRoute._addFileChildren(
  UsersIdRouteRouteChildren,
)

interface UsersRouteRouteChildren {
  UsersIdRouteRoute: typeof UsersIdRouteRouteWithChildren
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersIdRouteRoute: UsersIdRouteRouteWithChildren,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRouteRoute: CollectionsRouteRouteWithChildren,
  FragrancesRouteRoute: FragrancesRouteRouteWithChildren,
  SearchRouteRoute: SearchRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  AuthAccountRecoveryRoute: AuthAccountRecoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
