/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserIdImport } from './routes/user/$id'
import { Route as UserIdIndexImport } from './routes/user/$id/index'
import { Route as FragranceIdIndexImport } from './routes/fragrance/$id/index'
import { Route as UserIdReviewsImport } from './routes/user/$id/reviews'
import { Route as UserIdLikesImport } from './routes/user/$id/likes'
import { Route as FragranceIdReviewImport } from './routes/fragrance/$id/review'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdRoute = UserIdImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRoute,
} as any)

const UserIdIndexRoute = UserIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserIdRoute,
} as any)

const FragranceIdIndexRoute = FragranceIdIndexImport.update({
  id: '/fragrance/$id/',
  path: '/fragrance/$id/',
  getParentRoute: () => rootRoute,
} as any)

const UserIdReviewsRoute = UserIdReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserIdRoute,
} as any)

const UserIdLikesRoute = UserIdLikesImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => UserIdRoute,
} as any)

const FragranceIdReviewRoute = FragranceIdReviewImport.update({
  id: '/fragrance/$id/review',
  path: '/fragrance/$id/review',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdImport
      parentRoute: typeof rootRoute
    }
    '/fragrance/$id/review': {
      id: '/fragrance/$id/review'
      path: '/fragrance/$id/review'
      fullPath: '/fragrance/$id/review'
      preLoaderRoute: typeof FragranceIdReviewImport
      parentRoute: typeof rootRoute
    }
    '/user/$id/likes': {
      id: '/user/$id/likes'
      path: '/likes'
      fullPath: '/user/$id/likes'
      preLoaderRoute: typeof UserIdLikesImport
      parentRoute: typeof UserIdImport
    }
    '/user/$id/reviews': {
      id: '/user/$id/reviews'
      path: '/reviews'
      fullPath: '/user/$id/reviews'
      preLoaderRoute: typeof UserIdReviewsImport
      parentRoute: typeof UserIdImport
    }
    '/fragrance/$id/': {
      id: '/fragrance/$id/'
      path: '/fragrance/$id'
      fullPath: '/fragrance/$id'
      preLoaderRoute: typeof FragranceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexImport
      parentRoute: typeof UserIdImport
    }
  }
}

// Create and export the route tree

interface UserIdRouteChildren {
  UserIdLikesRoute: typeof UserIdLikesRoute
  UserIdReviewsRoute: typeof UserIdReviewsRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
}

const UserIdRouteChildren: UserIdRouteChildren = {
  UserIdLikesRoute: UserIdLikesRoute,
  UserIdReviewsRoute: UserIdReviewsRoute,
  UserIdIndexRoute: UserIdIndexRoute,
}

const UserIdRouteWithChildren =
  UserIdRoute._addFileChildren(UserIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/fragrance/$id/review': typeof FragranceIdReviewRoute
  '/user/$id/likes': typeof UserIdLikesRoute
  '/user/$id/reviews': typeof UserIdReviewsRoute
  '/fragrance/$id': typeof FragranceIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fragrance/$id/review': typeof FragranceIdReviewRoute
  '/user/$id/likes': typeof UserIdLikesRoute
  '/user/$id/reviews': typeof UserIdReviewsRoute
  '/fragrance/$id': typeof FragranceIdIndexRoute
  '/user/$id': typeof UserIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/fragrance/$id/review': typeof FragranceIdReviewRoute
  '/user/$id/likes': typeof UserIdLikesRoute
  '/user/$id/reviews': typeof UserIdReviewsRoute
  '/fragrance/$id/': typeof FragranceIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user/$id'
    | '/fragrance/$id/review'
    | '/user/$id/likes'
    | '/user/$id/reviews'
    | '/fragrance/$id'
    | '/user/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fragrance/$id/review'
    | '/user/$id/likes'
    | '/user/$id/reviews'
    | '/fragrance/$id'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/user/$id'
    | '/fragrance/$id/review'
    | '/user/$id/likes'
    | '/user/$id/reviews'
    | '/fragrance/$id/'
    | '/user/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserIdRoute: typeof UserIdRouteWithChildren
  FragranceIdReviewRoute: typeof FragranceIdReviewRoute
  FragranceIdIndexRoute: typeof FragranceIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserIdRoute: UserIdRouteWithChildren,
  FragranceIdReviewRoute: FragranceIdReviewRoute,
  FragranceIdIndexRoute: FragranceIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user/$id",
        "/fragrance/$id/review",
        "/fragrance/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/user/$id": {
      "filePath": "user/$id.tsx",
      "children": [
        "/user/$id/likes",
        "/user/$id/reviews",
        "/user/$id/"
      ]
    },
    "/fragrance/$id/review": {
      "filePath": "fragrance/$id/review.tsx"
    },
    "/user/$id/likes": {
      "filePath": "user/$id/likes.tsx",
      "parent": "/user/$id"
    },
    "/user/$id/reviews": {
      "filePath": "user/$id/reviews.tsx",
      "parent": "/user/$id"
    },
    "/fragrance/$id/": {
      "filePath": "fragrance/$id/index.tsx"
    },
    "/user/$id/": {
      "filePath": "user/$id/index.tsx",
      "parent": "/user/$id"
    }
  }
}
ROUTE_MANIFEST_END */
